name: blue-build-nvidia
description: My personal Fedora Atomic image, powered by BlueBuild's infrastructure

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://raw.githubusercontent.com/IverCoder/blue-build/main/repos/shiftkey-packages.repo
    install:
      - github-desktop
      - gnome-console
      - powertop
      - waydroid
    remove:
      - firefox
      - firefox-langpacks
      - gnome-terminal
      - gnome-terminal-nautilus

  - type: default-flatpaks
    notify: true
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub"
      install:
        - io.github.Foldex.AdwSteamGtk # AdwSteamGtk
        - io.bassi.Amberol # Amberol
        - org.gnome.gitlab.somas.Apostrophe # Apostrophe
        - cc.arduino.IDE2 # Arduino IDE v2
        - org.kde.ark # Ark
        - de.haeckerfelix.AudioSharing # Audio Sharing
        - com.raggesilver.BlackBox # Black Box
        - com.usebottles.bottles # Bottles
        - org.gnome.Boxes # Boxes
        - org.gnome.Builder # Builder
        - org.gnome.Calculator # Calculator
        - org.gnome.Calendar # Calendar
        - org.gnome.Snapshot # Camera
        - hu.kramo.Cartridges # Cartridges
        - io.github.celluloid_player.Celluloid # Celluloid
        - org.gnome.Characters # Characters
        - com.clarahobbs.chessclock # Chess Clock
        - org.gnome.clocks # Clocks
        - dev.geopjr.Collision # Collision
        - com.belmoussaoui.Decoder # Decoder
        - com.mattjakeman.ExtensionManager # Extension Manager
        - org.mozilla.firefox # Firefox
        - com.github.tchx84.Flatseal # Flatseal
        - it.mijorus.gearlever # Gear Lever
        - org.gnome.Chess # GNOME Chess
        - org.gimp.GIMP # GNU Image Manipulation Program
        - com.github.GradienceTeam.Gradience # Gradience
        - org.gnome.Loupe # Image Viewer
        - org.gnome.World.Iotas # Iotas
        - io.github.seadve.Kooha # Kooha
        - org.kde.krita # Krita
        - org.libreoffice.LibreOffice # LibreOffice
        - org.gnome.Logs # Logs
        - io.missioncenter.MissionCenter # Mission Center
        - com.obsproject.Studio # OBS Studio
        - org.onlyoffice.desktopeditors # ONLYOFFICE Desktop Editors
        - org.gnome.Photos # Photos
        - org.prismlauncher.PrismLauncher # Prism Launcher
        - it.mijorus.smile # Smile
        - com.valvesoftware.Steam # Steam
        - org.gnome.NautilusPreviewer # Sushi
        - io.github.nokse22.teleprompter # Teleprompter
        - org.gnome.TextEditor # Text Editor
        - io.github.flattool.Warehouse # Warehouse
        - app.drey.Warp # Warp

  - type: signing
